### ISSUE TITLE
err run 1_geometry_and_dynamics.ipynb

### ISSUE THREAD

**Issue by dbdxnuliba** [MeMory-of-MOtion/summer-school#4]
http://127.0.0.1:8888/notebooks/summer-school/tutorials/pinocchio/1_geometry_and_dynamics.ipynb
![image](https://user-images.githubusercontent.com/13350158/230912562-93283499-fb89-49ce-a35d-d0084062ab27.png)

when I run 
```
cost = Cost3d(rmodel, rdata, viz=viz)
qguess = robot.q0.copy()
qopt = fmin_bfgs(cost.calc, qguess, callback=cost.callback)
viz.display(qopt)
```
it shows err info:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-25-a4ab10297fa2> in <module>
----> 1 cost = Cost3d(rmodel, rdata, viz=viz)
      2 qguess = robot.q0.copy()
      3 qopt = fmin_bfgs(cost.calc, qguess, callback=cost.callback)
      4 viz.display(qopt)

NameError: name 'Cost3d' is not defined

**Comment by cmastalli** [comment]
The notebook is working well and you are not running the previous cell. This cell loads the above-mentioned cost. Please work out the code carefully before creating any issues.
